### ISSUE TITLE
Add Windows CI

### ISSUE THREAD

**Issue by cooperlees** [facebookincubator/ptr#2]
- Add Windows CI and make code pass on POSIX + Windows Platforms.

**Comment by aijayadams** [comment]
I am not having much love with the symlink in the repo under Windows.
Python 3.6.2

```
(testvenv) PS C:\Users\Aijay\projects\ptr> ptr -b . -k
Traceback (most recent call last):
  File "C:\Users\Aijay\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Aijay\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Aijay\projects\testvenv\Scripts\ptr.exe\__main__.py", line 5, in <module>
  File "c:\users\aijay\projects\testvenv\lib\site-packages\ptr.py", line 62, in <module>
    CONFIG = _config_read(CWD) or _config_default()
  File "c:\users\aijay\projects\testvenv\lib\site-packages\ptr.py", line 51, in _config_read
    cp.read(str(ptrconfig_path))
  File "C:\Users\Aijay\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Users\Aijay\AppData\Local\Programs\Python\Python36-32\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: 'C:\\Users\\Aijay\\projects\\ptr\\.ptrconfig', line: 1
'ptrconfig.sample'
```

**Comment by cooperlees** [comment]
Neither - That's why #25 removes the symlink 💃

**Comment by cooperlees** [comment]
Ok - #25 now has unit tests passing. Now to just get `ptr` itself running (integration tests) on Azure Windows to ensure we get it working and it stays working.

**Comment by cooperlees** [comment]
Logged an issue with Black maintainers to see why `black.exe` hangs with Python 3.7: https://github.com/ambv/black/issues/728

**Comment by cooperlees** [comment]
We have Windows CI running and have tested using it. Please open follow up Issues if Windows bugs are found.
