### ISSUE TITLE
Add Support for Classes and Custom Commands in seutp.py AST Parsing

### ISSUE THREAD

**Issue by omikader** [facebookincubator/ptr#54]
Thanks for logging an issue with `ptr`. Here are some questions to help try 
and pull out as much information possible to help us help you!

## How is `ptr` not doing what you expect?
Unable to run `ptr` on a project where `setup.py` includes a custom build command definition.

## What is your suggestion to make this better?
Add AST parsing support for custom commands and other class definitions.

## Code/Bug example?
```
root@faa971b550dd:/usr/local/tglib# ptr -k
[2019-08-06 19:50:50,751] INFO: Starting /usr/local/bin/ptr (ptr.py:1073)
Traceback (most recent call last):
  File "/usr/local/bin/ptr", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/ptr.py", line 1090, in main
    args.venv_timeout,
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/ptr.py", line 965, in async_main
    base_path, stats, run_disabled, print_non_configured
  File "/usr/local/lib/python3.7/dist-packages/ptr.py", line 337, in _get_test_modules
    if target.id == "ptr_params":  # type: ignore
```

## How can a developer reproduce this?

Add a custom command to `setup.py` using the instructions [here](https://jichu4n.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy/).

**Comment by omikader** [comment]
Resolved, thanks!

**Comment by cooperlees** [comment]
Awesome. I better merge the fix 📦  ...
